name: infra-k8s-in-action
on:
  workflow_dispatch: 
#   push:
#     branches:
#         - dev 
#         - 'feature/*'

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: tf-src/envs/dev/
        run: |
          terraform init \
            -backend-config "bucket=terraform-state-dev-samboo" \
            -backend-config "key=dev/k8s-in-action/tfstate-k8s-in-action-app.tfstate"
      
      - name: Terraform Format
        working-directory: tf-src/envs/dev/
        run: terraform fmt

      - name: Terraform validate
        id: validate
        working-directory: tf-src/envs/dev/
        run: terraform validate

      - name: Terraform plan
        id: plan
        working-directory: tf-src/envs/dev/
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform apply
        id: apply
        working-directory: tf-src/envs/dev/
        run: terraform apply -auto-approve -input=false -parallelism=1 planfile  # build resources 1 at a time 